### ISSUE TITLE
Add BioTime database functions

### ISSUE THREAD

**Issue by ha0ye** [weecology/MATSS#116]
Current status:
* downloaded BioTime database in mySQL
* imported and read in BioTime tables

TODO:
* verify and understand linkages between tables
* check how BioTime computes abundance and biomass for individual datasets
* develop methods to generate community time series datasets

**Comment by ha0ye** [comment]
It looks like retriever already has a [script for getting BioTime data](https://github.com/weecology/retriever/blob/master/scripts/biotime.json), but we may want to check:
- [ ] if all the metadata are present
- [ ] if the script should be updated to the newest version on Zenodo - https://zenodo.org/record/2602708

**Comment by ha0ye** [comment]
Current concerns about Sevilleta dataset in BioTime:
* every stake is recorded as a site
* biomass and abundances don't make sense (unclear if the raw data is different or processed unusually / incorrectly)
* are these issues also present in other datasets?

**Comment by gmyenni** [comment]
Biotime raw data appear to be fine in general. In the raw data the abundances and biomasses are not computed, they are just the data that were provided to them (eg Portal has no biomasses, because we didn't provide them; the Sev apparently provided data at the stake level and erroneous weights).

Database structure and more: http://biotime.st-andrews.ac.uk/downloads/interactBioTIME.html
