### ISSUE TITLE
2/21 meeting

### ISSUE THREAD

**Issue by diazrenata** [weecology/MATSS#86]
I'm still in the process of figuring out how to work with drake (particularly passing arguments around vs. hardcoding things), so I have less of a long view of the project at the moment. @ha0ye, these are my thoughts re: today's meeting - do you have anything to add or adjust? 

I'm thinking there are a couple of things we should touch on with everyone: 
- Document & communicate data importing workflow to the group

and then break out and work on issues? These are the ones I see as important at the moment:
- Cache workflow, storage
- Adding and cleaning datasets (check BBS data?)
- Update MATSS-LDATS initial analysis to use MATSS functions
- Document how to add analyses to the plan

**Comment by ha0ye** [comment]
Looks good to me.

I can probably spend some time working on a vignette to document how to work with Drake...

**Comment by diazrenata** [comment]
frequent issues:
* flexibility with the datasets: capacity to run if a dataset is missing, run with a single additional dataset, ETC. May include changing the checks around local datasets, or storing data similarly to how we store the cache?
* automate/smooth out updating dependencies
* clarify which objects are being checked; what objects in the drake cache are catching the changes that matter; how to structure pipeline so that the appropriate checks run

**Comment by ha0ye** [comment]
Some notes on the drake caching:
* there's a section in the manual that discusses [triggers for (re)building](https://ropenscilabs.github.io/drake-manual/triggers.html), but I haven't looked at it thoroughly yet.

Drake has special functions to keep track of external files. This is so that it can probably distinguish between dependencies on e.g. character strings and files.

For example:
```r
# this should never need to be re-built
drake_plan(status = message("hello"))

# we want this to re-build when data.csv changes, but it doesn't
drake_plan(dat = read.csv("data.csv"))

# this will properly re-build when data.csv changes
drake_plan(dat = read.csv(file_in("data.csv")))
```

This is why we use `knitr_in()` for the Rmarkdown report, so that drake can check if the code chunks there change and the report needs to be re-rendered.
